apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubiz-help-ai
  namespace: rubiz
  labels:
    app: rubiz-help-ai
    brand: rubiz
    environment: uat
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: rubiz-help-ai
  template:
    metadata:
      labels:
        app: rubiz-help-ai
        brand: rubiz
        environment: uat
        version: v1
    spec:
      imagePullSecrets:
        - name: gcr-flash
      containers:
        - name: rubiz-help-ai
          # Uses flash-help-ai Docker image - no brand-specific build needed
          image: gcr.io/flashvpn-253908/flash-help-ai:latest
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "uat"
            - name: PORT
              value: "3000"
            - name: HELP_DOMAIN
              value: "guides.rubizvpn.com"
            - name: CHROMA_COLLECTION
              value: "rubiz-help"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: CHROMA_HOST
              value: "chromadb.default.svc.cluster.local"
            - name: CHROMA_PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "info"
            - name: MAX_RETRIES
              value: "3"
            - name: TIMEOUT_MS
              value: "30000"
            - name: RATE_LIMIT_MAX
              value: "100"
            - name: RATE_LIMIT_WINDOW_MS
              value: "60000"
          envFrom:
            - secretRef:
                name: rubiz-help-ai-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: rubiz-help-ai
  namespace: rubiz
  labels:
    app: rubiz-help-ai
    brand: rubiz
    environment: uat
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: rubiz-help-ai

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rubiz-help-ai-hpa
  namespace: rubiz
  labels:
    app: rubiz-help-ai
    brand: rubiz
    environment: uat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rubiz-help-ai
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
